### ISSUE TITLE
x not in tuple when grouping by time in holomap

### ISSUE THREAD

**Issue by ahuang11** [pyviz/geoviews#241] opened 2018-10-12 21:01 UTC
```
ValueError: tuple.index(x): x not in tuple

:Layout
   .HoloMap.I  :HoloMap   [time]
      :Image   [lon,lat]   (air)
   .HoloMap.II :HoloMap   [time]
      :Curve   [lat]   (air)
```

```
import hvplot.xarray
import xarray as xr

LAT = 'lat'
LON = 'lon'
ds = xr.tutorial.load_dataset('air_temperature').isel(time=[0, 1, 2, 3])
ds['air'].hvplot(LON, LAT, geo=True, groupby='time', dynamic=False) + ds['air'].rename({LAT: 'Latitude'}).mean(LON).hvplot(groupby='time', dynamic=False)
```

**Comment by philippjfr** [comment] 2019-10-08 19:07
No longer raising the same error but the curve doesn't display in this setup.

**Comment by philippjfr** [comment] 2019-10-24 16:57
The mentioned bug is just a duplicate of #240

**Closed by philippjfr** 2019-10-24 16:57 UTC
