### ISSUE TITLE
global data with negative longitude disappears on 2nd render when using tiles

### ISSUE THREAD

**Issue by rsignell-usgs** [pyviz/geoviews#362] opened 2019-10-04 00:07 UTC
This is kind of bizarre, but when visualizing this dataset:
```python
url = 'http://thredds.unidata.ucar.edu/thredds/dodsC/grib/NCEP/WW3/Global/Best'

import xarray as xr
import hvplot.xarray 
import geoviews as gv

ds = xr.open_dataset(url)
```
we can combine a quadmesh with a coastline just fine:
```python
ds.Wind_speed_surface.hvplot.quadmesh(x='lon',y='lat',rasterize=True, geo=True) *  gv.feature.coastline
```
![2019-10-03_20-11-39](https://user-images.githubusercontent.com/1872600/66172616-591b2480-e61a-11e9-921f-1017ec7b9d2a.png)

but combining a quadmesh with a tile source:
```python
ds.Wind_speed_surface.hvplot.quadmesh(x='lon',y='lat',rasterize=True, geo=True) *  gv.tile_sources.EsriImagery
```
we get the correct visualization at first, but then it's quickly replaced with a visualization where the data with longitude less than zero disappear (and the quadmesh visualization changes to span the range of the data greater than zero):
![hvplot](https://user-images.githubusercontent.com/1872600/66172674-aac3af00-e61a-11e9-891b-d46a22a485f0.gif)

**Comment by philippjfr** [comment] 2019-10-04 00:36
Seems to be something to do with wrapping the longitudes, this fixes it:

```
ds['lon'] = np.where(ds['lon']>180, ds['lon']-360, ds['lon'])
```

**Comment by rsignell-usgs** [comment] 2019-10-04 11:55
@philippjfr , Thanks!

Is this a workaround for a problem that you will eventually be able to handle in HoloViz?
Or do you think users going forward will need to apply that line of code in their notebooks?

**Comment by philippjfr** [comment] 2019-10-04 12:10
>Is this a workaround for a problem that you will eventually be able to handle in HoloViz?

I would think we can fix it, especially since it seems this is handled correctly on the first render.

**Comment by philippjfr** [comment] 2019-10-04 12:13
I suspect this happens because the frontend sends back the axis ranges which range from -180-180 which then clips the data. On first render the ranges are computed from the data and the Image projection code correctly wraps the data (although the seam at 0 longitude isn't great either).

**Comment by philippjfr** [comment] 2019-10-04 12:14
@rsignell-usgs Actually there is a simpler fix, you can project the data before rasterizing:

```python
ds.Wind_speed_surface.hvplot.quadmesh(x='lon',y='lat',rasterize=True, geo=True, project=True, width=600) *  gv.tile_sources.EsriImagery
```

**Comment by rsignell-usgs** [comment] 2019-10-04 12:24
@philippjfr nice!   Works!
Just curious, did you get these warnings also when using `project=True`?:
```
/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/function_base.py:1273: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/function_base.py:1273: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
/srv/conda/envs/notebook/lib/python3.7/site-packages/numpy/lib/function_base.py:1273: RuntimeWarning: invalid value encountered in subtract
  a = op(a[slice1], a[slice2])
```

**Comment by philippjfr** [comment] 2019-10-04 12:25
Yeah, we should silence them internally.

**Comment by philippjfr** [comment] 2019-10-24 18:07
Duplicate of #344

**Closed by philippjfr** 2019-10-24 18:07 UTC
