### ISSUE TITLE
Viewing a GeoTIFF with Geoviews is cropping the right edge

### ISSUE THREAD

**Issue by asmith26** [pyviz/geoviews#310] opened 2019-04-10 12:05 UTC
### Geoviews:

```
tif = gv.load_tiff("/path/to/some.tif", nan_nodata=True)

gv.tile_sources.Wikipedia * tif
```

![image](https://user-images.githubusercontent.com/6988036/55870048-a9d82600-5b7f-11e9-8ee7-1e13986864c5.png)

### QGIS:

![image](https://user-images.githubusercontent.com/6988036/55870069-b52b5180-5b7f-11e9-8fa1-143bf4dc8a4a.png)

This seems to only happen to a certain set of TIFFs that were produced in the same way (reading TIFFs produced elsewhere read fine) - that said QGIS display them fine. Is there something/some attribute in these TIFFs that make GeoViews crop the right side?

(I could try and make a more reproducible example using an online TIFF if you know of such a URL? Just thought I'd initially check I'm not doing anything wrong first.)

Many thanks!

**Comment by philippjfr** [comment] 2019-04-10 12:21
>(I could try and make a more reproducible example using an online TIFF if you know of such a URL? Just thought I'd initially check I'm not doing anything wrong first.)

That would certainly help. The actual I/O functionality here is provided by the ``xarray.open_rasterio`` function so it may also help to check whether that already has these issues or whether it is something in the geoviews wrapper that applies coordinate transforms that's causing this.

**Comment by asmith26** [comment] 2019-04-10 19:19
Thanks for the response.

I have investigated further and have realised that GeoViews is cropping to the UTM bounds (in particular, not only cropping at the right but also the left for TIFFs wide enough).

I guess this makes sense (as accuracy diminishes outside of a UTM zone). **Should we add an argument in e.g. `gv.load_tif(...)` to specify if the data should be cropped or not?**

(I'm not entirely sure where the cropping is happening, but xarray and rasterio display the entire image, so it must be in GeoViews)

**Comment by philippjfr** [comment] 2019-10-24 17:17
Will close as duplicate of https://github.com/pyviz/geoviews/issues/328

**Closed by philippjfr** 2019-10-24 17:17 UTC
