### ISSUE TITLE
Linked "lat" Axis "Layout

### ISSUE THREAD

**Issue by ahuang11** [pyviz/geoviews#239] opened 2018-10-12 16:36 UTC
```
import xarray as xr
ds = xr.tutorial.load_dataset('air_temperature').isel(time=0)
ds['air'].hvplot(LON, LAT, geo=True) + ds['air'].mean(LON).hvplot(invert=True)
```

**Comment by philippjfr** [comment] 2018-10-12 16:45
I'll close as a duplicate of #240

**Closed by philippjfr** 2018-10-12 16:45 UTC
